#!/usr/bin/env bash
# =============================================================================
# deploy_frontend.sh — Sync the static frontend to S3 and bust CloudFront cache
#
# Usage:
#   ./deploy_frontend.sh
#
# Run this after editing frontend/index.html, style.css, or main.js.
# Content JSON (generated by run_daily.sh) is never touched by this script.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

if [ -t 1 ]; then
  GREEN="\033[0;32m"; YELLOW="\033[0;33m"; RED="\033[0;31m"; RESET="\033[0m"
else
  GREEN=""; YELLOW=""; RED=""; RESET=""
fi

info()  { echo -e "${GREEN}[deploy]${RESET} $*"; }
error() { echo -e "${RED}[deploy]${RESET} $*" >&2; }

# ── Load .env ─────────────────────────────────────────────────────────────────

if [ ! -f "$ENV_FILE" ]; then
  error ".env not found. Copy .env.example and fill in your AWS credentials."
  exit 1
fi

set -a; source "$ENV_FILE"; set +a

if [ -z "${S3_BUCKET:-}" ] || [ -z "${AWS_ACCESS_KEY_ID:-}" ]; then
  error "S3_BUCKET and AWS credentials must be set in .env"
  exit 1
fi

# ── Generate the per-language HTML shells (frontend/<lang>/…) ──────────────────
# The English page is the template; this writes the de/es/it/ja/fr copies the sync
# below uploads. Best-effort: a generator hiccup must not block the asset deploy.

info "Generating per-language HTML shells"
python3 -m content_pipeline.agent.i18n_html "$SCRIPT_DIR/frontend" || \
  info "localized HTML generation skipped (generator unavailable)"

# ── Sync frontend/ → S3 ───────────────────────────────────────────────────────
# Protect EVERY language's generated JSON/audio/images from --delete: the root
# English tree (content/, preview/) AND each translation tree (<lang>/content/, …).

info "Syncing frontend/ → s3://$S3_BUCKET/"
aws s3 sync "$SCRIPT_DIR/frontend/" "s3://$S3_BUCKET/" \
  --delete \
  --exclude "content/*" \
  --exclude "preview/*" \
  --exclude "*/content/*" \
  --exclude "*/preview/*" \
  --exclude "*.md" \
  --exclude ".DS_Store" \
  --region "${AWS_REGION:-eu-west-1}"

# ── Invalidate CloudFront ──────────────────────────────────────────────────────

if [ -n "${CLOUDFRONT_DISTRIBUTION_ID:-}" ]; then
  info "Invalidating CloudFront distribution $CLOUDFRONT_DISTRIBUTION_ID"
  aws cloudfront create-invalidation \
    --distribution-id "$CLOUDFRONT_DISTRIBUTION_ID" \
    --paths "/*" \
    --query 'Invalidation.Status' --output text
else
  info "CLOUDFRONT_DISTRIBUTION_ID not set — skipping invalidation"
fi

info "Done. Site will be live within ~30 seconds."
