#!/usr/bin/env bash
# =============================================================================
# deploy_frontend.sh — Sync the static frontend to S3 and bust CloudFront cache
#
# Usage:
#   ./deploy_frontend.sh
#
# Run this after editing frontend/index.html, style.css, or main.js.
# Content JSON (generated by run_daily.sh) is never touched by this script.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

if [ -t 1 ]; then
  GREEN="\033[0;32m"; YELLOW="\033[0;33m"; RED="\033[0;31m"; RESET="\033[0m"
else
  GREEN=""; YELLOW=""; RED=""; RESET=""
fi

info()  { echo -e "${GREEN}[deploy]${RESET} $*"; }
error() { echo -e "${RED}[deploy]${RESET} $*" >&2; }

# ── AWS credentials — sourced from 1Password (the Agent Credentials vault) ──────
#
# All deploy creds live in ONE 1Password item in the AGENT-accessible vault, so an
# unattended service-account op token resolves them. GOTCHA: a service account MUST
# use a FULLY-QUALIFIED reference — op://<vault>/<item>/<field>; an unqualified
# op://<item>/<field> fails with "a vault query must be provided when this command
# is called by a service account". The one item carries the access key (username),
# secret (credential), s3 bucket, region and CloudFront distribution id.
OP_ITEM="${CRAICGPT_OP_ITEM:-op://AgentCredentials/AWS craicgpt-publish IAM}"

if command -v op >/dev/null 2>&1 && op read "$OP_ITEM/region" >/dev/null 2>&1; then
  info "Sourcing AWS creds from 1Password ($OP_ITEM)"
  export AWS_ACCESS_KEY_ID="$(op read "$OP_ITEM/username")"
  export AWS_SECRET_ACCESS_KEY="$(op read "$OP_ITEM/credential")"
  S3_BUCKET="${S3_BUCKET:-$(op read "$OP_ITEM/s3 bucket")}"
  CLOUDFRONT_DISTRIBUTION_ID="${CLOUDFRONT_DISTRIBUTION_ID:-$(op read "$OP_ITEM/cloudfront distribution id")}"
  AWS_REGION="${AWS_REGION:-$(op read "$OP_ITEM/region")}"
else
  # Fallback: an optional .env (its op:// refs may be unqualified and fail for a
  # service account — ignored) then the ambient AWS credentials / shell environment.
  info "1Password item not reachable — falling back to .env / ambient AWS creds"
  if [ -f "$ENV_FILE" ]; then set -a; source "$ENV_FILE" 2>/dev/null || true; set +a; fi
  case "${AWS_ACCESS_KEY_ID:-}" in ""|op://*) unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY 2>/dev/null || true ;; esac
  S3_BUCKET="${S3_BUCKET:-craicgpt-ie-production}"
  CLOUDFRONT_DISTRIBUTION_ID="${CLOUDFRONT_DISTRIBUTION_ID:-E1DJEM9WBUG1C1}"
  AWS_REGION="${AWS_REGION:-eu-west-1}"
fi

if ! aws sts get-caller-identity >/dev/null 2>&1; then
  error "no authenticated AWS session (1Password item unreachable and no ambient creds)."
  exit 1
fi

# ── Generate the per-language HTML shells (frontend/<lang>/…) ──────────────────
# The English page is the template; this writes the de/es/it/ja/fr copies the sync
# below uploads. Best-effort: a generator hiccup must not block the asset deploy.

info "Generating per-language HTML shells"
python3 -m content_pipeline.agent.i18n_html "$SCRIPT_DIR/frontend" || \
  info "localized HTML generation skipped (generator unavailable)"

# ── Sync frontend/ → S3 ───────────────────────────────────────────────────────
# Protect EVERY language's generated JSON/audio/images from --delete: the root
# English tree (content/, preview/) AND each translation tree (<lang>/content/, …).

info "Syncing frontend/ → s3://$S3_BUCKET/"
aws s3 sync "$SCRIPT_DIR/frontend/" "s3://$S3_BUCKET/" \
  --cache-control "no-cache" \
  --delete \
  --exclude "content/*" \
  --exclude "preview/*" \
  --exclude "*/content/*" \
  --exclude "*/preview/*" \
  --exclude "*.md" \
  --exclude ".DS_Store" \
  --region "${AWS_REGION:-eu-west-1}"

# ── Invalidate CloudFront ──────────────────────────────────────────────────────

if [ -n "${CLOUDFRONT_DISTRIBUTION_ID:-}" ]; then
  info "Invalidating CloudFront distribution $CLOUDFRONT_DISTRIBUTION_ID"
  aws cloudfront create-invalidation \
    --distribution-id "$CLOUDFRONT_DISTRIBUTION_ID" \
    --paths "/*" \
    --query 'Invalidation.Status' --output text
else
  info "CLOUDFRONT_DISTRIBUTION_ID not set — skipping invalidation"
fi

info "Done. Site will be live within ~30 seconds."
