"""
content_pipeline/providers/litellm.py
======================================
LiteLLM-proxy provider for the daily content engine, plus the **local-first /
frontier-fallback** wrapper that underpins the whole open-source-first strategy.

TUTORIAL: base_url is the only thing that changes
-------------------------------------------------
Like ``lmstudio.py``, this is just ``ChatOpenAI`` with a custom ``base_url`` —
but pointed at the grazlab LiteLLM proxy instead of a single LM Studio box.
LiteLLM routes by model name across the whole fleet (M3 Ultra, DGX Spark, a
frontier provider), so the same chain code reaches any of them.

TUTORIAL: graceful degradation, made honest
-------------------------------------------
We *want* local open-source models to do the work — that's the point of the
project, and it's what the published "generated by …" note should usually say.
But a flaky local agentic run shouldn't produce a dud paper. ``run_with_fallback``
tries the local model, and only if it raises or fails a validation check does it
retry on a frontier model. Either way it returns a :class:`GenerationResult` that
records *which* model actually ran (so attribution is truthful) and *why* the
local one failed (so ``running-eval-loop`` can turn it into a regression case).
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any, Callable, Optional

from langchain_core.language_models import BaseChatModel

from content_pipeline.content_config import content_cfg

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────────────
# Result type
# ─────────────────────────────────────────────────────────────────────────────
@dataclass
class GenerationResult:
    """Outcome of a local-first generation attempt.

    Attributes:
        output:     The value returned by the (local or fallback) callable.
        model_used: The model route that actually produced ``output`` — this is
                    what gets stamped into the published attribution note.
        fell_back:  True if the local model failed and the fallback produced it.
        error:      The local failure reason (exception text or validation
                    message) when ``fell_back`` is True; otherwise None. Fed to
                    the eval feedback loop.
    """

    output: Any
    model_used: str
    fell_back: bool
    error: Optional[str] = None


# ─────────────────────────────────────────────────────────────────────────────
# Local-first → frontier-fallback wrapper
# ─────────────────────────────────────────────────────────────────────────────
def run_with_fallback(
    fn: Callable[[str], Any],
    *,
    local_model: str,
    fallback_model: str,
    validate: Optional[Callable[[Any], bool]] = None,
) -> GenerationResult:
    """Run ``fn(model)`` on the local model, falling back to a frontier model.

    Args:
        fn: A callable that takes a model route and returns generated output
            (e.g. a closure that invokes an LCEL chain with that model). It is
            called at most twice: once with ``local_model``, then — only on
            failure — once with ``fallback_model``.
        local_model: The preferred open-source route (tried first).
        fallback_model: The frontier route used only if the local attempt fails.
        validate: Optional predicate; output for which it returns False is
            treated as a failure and triggers fallback. Defaults to a truthiness
            check, so ``None``/``""``/empty results fall back.

    Returns:
        A :class:`GenerationResult`.

    Raises:
        The fallback's exception if BOTH the local and fallback attempts fail —
        we never return a silent dud.
    """
    check = validate if validate is not None else bool

    # ── Attempt 1: local open-source model ────────────────────────────────────
    local_error: Optional[str] = None
    try:
        output = fn(local_model)
        if check(output):
            logger.info("[fallback] local model %s succeeded", local_model)
            return GenerationResult(output=output, model_used=local_model, fell_back=False)
        local_error = f"validation failed for output from {local_model}"
        logger.warning("[fallback] %s", local_error)
    except Exception as exc:  # noqa: BLE001 — any local failure is a fallback trigger
        local_error = f"{type(exc).__name__}: {exc}"
        logger.warning("[fallback] local model %s raised: %s", local_model, local_error)

    # ── Attempt 2: frontier fallback ──────────────────────────────────────────
    logger.info("[fallback] retrying on frontier model %s", fallback_model)
    output = fn(fallback_model)  # if this raises, it propagates — no silent dud
    if not check(output):
        raise RuntimeError(
            f"fallback model {fallback_model} also produced invalid output "
            f"(local failure was: {local_error})"
        )
    return GenerationResult(
        output=output,
        model_used=fallback_model,
        fell_back=True,
        error=local_error,
    )


# ─────────────────────────────────────────────────────────────────────────────
# Provider factory
# ─────────────────────────────────────────────────────────────────────────────
def get_litellm_llm(
    model: str,
    *,
    temperature: Optional[float] = None,
    max_tokens: Optional[int] = None,
    extra_body: Optional[dict] = None,
) -> BaseChatModel:
    """Return a ChatOpenAI bound to the grazlab LiteLLM proxy for ``model``.

    Args:
        model: A route name from the grazlab catalog (e.g.
            ``m3/mlx/qwen3.6-35b-a3b-unsloth-8bit``).
        temperature: Override the configured default.
        max_tokens: Override the configured default.
        extra_body: Extra request body fields forwarded to the proxy — e.g.
            ``{"chat_template_kwargs": {"enable_thinking": False}}`` to turn off
            Qwen3.6's thinking preamble (which otherwise eats the token budget
            before any JSON is produced).

    Returns:
        A ``ChatOpenAI`` instance. Construction does no network I/O — the
        endpoint is only contacted on ``.invoke()``.
    """
    # Imported lazily so importing this module (and the pure fallback logic) does
    # not require the heavy langchain_openai stack — keeps unit tests fast.
    from langchain_openai import ChatOpenAI

    logger.info(
        "[provider:litellm] model=%s base_url=%s",
        model,
        content_cfg.litellm_base_url,
    )
    kwargs: dict = {}
    if extra_body:
        kwargs["extra_body"] = extra_body
    return ChatOpenAI(
        model=model,
        base_url=content_cfg.litellm_base_url,
        api_key=content_cfg.litellm_api_key,
        temperature=content_cfg.temperature if temperature is None else temperature,
        max_tokens=content_cfg.max_tokens if max_tokens is None else max_tokens,
        timeout=content_cfg.request_timeout,
        max_retries=2,
        **kwargs,
    )
